[package]
name = "swiffer"
version = "0.1.0"
edition = "2021"

[lib]
name = "packet_swiffer"
path = "src/lib/lib.rs"

[dependencies]
dns-parser = "0.8.0"
timer = "0.2.0"
chrono = "0.4.22"

[dependencies.pnet]
version = "0.30.0"
